# Generated by Django 5.1.3 on 2025-02-18 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='Název techniky')),
            ],
            options={
                'verbose_name': 'Technika',
                'verbose_name_plural': 'Techniky',
            },
        ),
        migrations.CreateModel(
            name='Obraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='obrazy/', verbose_name='Obrázek')),
                ('nazev', models.CharField(max_length=100, verbose_name='Název obrazu')),
                ('rok', models.IntegerField(verbose_name='Rok')),
                ('poznamky', models.TextField(verbose_name='Poznámky')),
                ('cena', models.IntegerField(verbose_name='Cena obrazu')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autori.autor', verbose_name='Autor obrazu')),
                ('technika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrazy.technika', verbose_name='Technika')),
            ],
            options={
                'verbose_name': 'Obraz',
                'verbose_name_plural': 'Obrazy',
            },
        ),
    ]
