# Generated by Django 5.1.3 on 2025-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='autori/', verbose_name='Fotka autora')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno autora')),
                ('narozen', models.DateField(verbose_name='Datum narození')),
                ('umrti', models.DateField(blank=True, null=True, verbose_name='Datum úmrtí')),
                ('zivotopis', models.TextField(verbose_name='Životopis')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autoři',
            },
        ),
    ]
