# Generated by Django 5.1.3 on 2024-11-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='obrazy/')),
                ('nazev', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('rok', models.IntegerField()),
                ('technika', models.CharField(max_length=100)),
                ('poznamky', models.TextField()),
                ('cena', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
